version: '3.8'

services:
  app:
    build: ./app
    container_name: tokenizer_app
    expose:
      - "8080"

  apache:
    build: ./apache
    container_name: tokenizer_apache
    ports:
      - "8080:80"
    depends_on:
      - app
