ServerName localhost

LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

Listen 80

<VirtualHost *:80>
    ProxyPreserveHost On

    # Forward EVERYTHING to Flask container
    ProxyPass / http://app:8080/
    ProxyPassReverse / http://app:8080/
</VirtualHost>
